[package]
name = "fig"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
figc = { path = "../figc" }
wasmer = "4.3.0"
clap = {version = "4.4.5", features = ["derive"]}
wasmprinter = "0.2.74"
log = "0.4"
env_logger = "0.11.3"
wasmer-wasix = "0.24.0"
